class_name GShapesDemoCatalog
extends RefCounted

const VISUAL_2D_DEMOS: Array[String] = [
	"res://Scenes/demos/animation_queue_demo.tscn",
	"res://Scenes/demos/animate_builder_demo.tscn",
	"res://Scenes/demos/text_and_tex_demo.tscn",
	"res://Scenes/demos/show_creation_demo.tscn",
	"res://Scenes/demos/fade_demo.tscn",
	"res://Scenes/demos/fade_transform_demo.tscn",
	"res://Scenes/demos/indication_demo.tscn",
	"res://Scenes/demos/lagged_group_demo.tscn",
	"res://Scenes/demos/timeline_controls_demo.tscn",
	"res://Scenes/demos/transform_demo.tscn",
	"res://Scenes/demos/transform_matching_shapes_demo.tscn",
	"res://Scenes/demos/graph_demo.tscn",
	"res://Scenes/demos/implicit_function_demo.tscn",
	"res://Scenes/demos/example_graph_scene_port.tscn",
	"res://Scenes/demos/composition_demo.tscn",
	"res://Scenes/demos/updater_graph_demo.tscn",
	"res://Scenes/demos/value_tracker_demo.tscn",
	"res://Scenes/demos/advanced_parity_demo.tscn",
	"res://Scenes/demos/example_coordinate_system_port.tscn",
	"res://Scenes/demos/morph_and_smooth_demo.tscn",
	"res://Scenes/demos/play_semantics_map_demo.tscn",
	"res://Scenes/demos/camera_framing_demo.tscn",
	"res://Scenes/demos/math_tex_parity_demo.tscn",
	"res://Scenes/demos/tex_engine_parity_demo.tscn",
	"res://Scenes/demos/decimal_number_parity_demo.tscn",
	"res://Scenes/demos/number_line_parity_demo.tscn",
	"res://Scenes/demos/angle_parity_demo.tscn",
	"res://Scenes/demos/dashed_line_parity_demo.tscn",
	"res://Scenes/demos/arrow_vector_parity_demo.tscn",
	"res://Scenes/demos/vector_field_parity_demo.tscn",
	"res://Scenes/demos/parametric_curve_parity_demo.tscn",
	"res://Scenes/demos/stream_lines_parity_demo.tscn",
	"res://Scenes/demos/polar_plot_parity_demo.tscn",
	"res://Scenes/demos/polar_plane_parity_demo.tscn",
	"res://Scenes/demos/complex_plane_parity_demo.tscn",
	"res://Scenes/demos/flow_particles_parity_demo.tscn",
	"res://Scenes/demos/conformal_grid_parity_demo.tscn",
	"res://Scenes/demos/complex_function_parity_demo.tscn",
	"res://Scenes/demos/fourier_curve_parity_demo.tscn",
	"res://Scenes/demos/epicycle_chain_parity_demo.tscn",
	"res://Scenes/demos/curvature_comb_parity_demo.tscn",
	"res://Scenes/demos/arc_length_markers_parity_demo.tscn",
	"res://Scenes/demos/tangent_frame_parity_demo.tscn",
	"res://Scenes/demos/curve_window_parity_demo.tscn",
	"res://Scenes/demos/normal_offset_parity_demo.tscn",
	"res://Scenes/demos/osculating_circle_parity_demo.tscn",
	"res://Scenes/demos/curve_intersections_parity_demo.tscn",
	"res://Scenes/demos/nearest_point_parity_demo.tscn",
	"res://Scenes/demos/riemann_rectangles_parity_demo.tscn",
	"res://Scenes/demos/graph_label_follower_parity_demo.tscn",
	"res://Scenes/demos/area_between_curves_parity_demo.tscn",
	"res://Scenes/demos/derivative_plot_parity_demo.tscn",
	"res://Scenes/demos/integral_plot_parity_demo.tscn",
	"res://Scenes/demos/secant_slope_group_parity_demo.tscn",
	"res://Scenes/demos/graph_roots_parity_demo.tscn",
	"res://Scenes/demos/graph_extrema_parity_demo.tscn",
	"res://Scenes/demos/graph_inflection_parity_demo.tscn",
	"res://Scenes/demos/newton_iteration_parity_demo.tscn",
	"res://Scenes/demos/bisection_iteration_parity_demo.tscn",
	"res://Scenes/demos/false_position_iteration_parity_demo.tscn",
	"res://Scenes/demos/fixed_point_iteration_parity_demo.tscn",
	"res://Scenes/demos/secant_iteration_parity_demo.tscn",
	"res://Scenes/demos/iteration_sequence_parity_demo.tscn",
	"res://Scenes/demos/orbit_diagram_parity_demo.tscn",
	"res://Scenes/demos/lyapunov_plot_parity_demo.tscn",
	"res://Scenes/demos/convergence_map_parity_demo.tscn",
	"res://Scenes/demos/return_map_parity_demo.tscn",
	"res://Scenes/demos/invariant_density_parity_demo.tscn",
	"res://Scenes/demos/recurrence_plot_parity_demo.tscn",
	"res://Scenes/demos/symbolic_dynamics_parity_demo.tscn",
	"res://Scenes/demos/autocorrelation_parity_demo.tscn",
	"res://Scenes/demos/power_spectrum_parity_demo.tscn",
	"res://Scenes/demos/block_entropy_parity_demo.tscn",
	"res://Scenes/demos/delayed_mutual_info_parity_demo.tscn",
	"res://Scenes/demos/permutation_entropy_parity_demo.tscn",
	"res://Scenes/demos/first_return_time_parity_demo.tscn",
	"res://Scenes/demos/recurrence_rate_curve_parity_demo.tscn",
	"res://Scenes/demos/entropy_rate_parity_demo.tscn",
	"res://Scenes/demos/return_time_cdf_parity_demo.tscn",
	"res://Scenes/demos/return_time_survival_parity_demo.tscn",
	"res://Scenes/demos/return_time_moments_parity_demo.tscn",
	"res://Scenes/demos/return_time_quantiles_parity_demo.tscn",
	"res://Scenes/demos/group_layout_parity_demo.tscn",
	"res://Scenes/demos/surrounding_rectangle_parity_demo.tscn",
	"res://Scenes/demos/brace_parity_demo.tscn",
	"res://Scenes/demos/mixed_mobject_parity_demo.tscn",
	"res://Scenes/demos/dynamic_helpers_demo.tscn",
	"res://Scenes/demos/path_follow_parity_demo.tscn",
	"res://Scenes/demos/animation_expansion_demo.tscn",
	"res://Scenes/demos/advanced_graphing_upgrade_demo.tscn",
]

const VISUAL_3D_DEMOS: Array[String] = [
	"res://Scenes/demos/surface_3d_demo.tscn",
	"res://Scenes/demos/three_d_parity_demo.tscn",
	"res://Scenes/demos/three_d_ecosystem_parity_demo.tscn",
	"res://Scenes/demos/three_d_group_transform_parity_demo.tscn",
	"res://Scenes/demos/three_d_camera_workflow_parity_demo.tscn",
	"res://Scenes/demos/three_d_camera_tour_parity_demo.tscn",
	"res://Scenes/demos/three_d_animation_effects_parity_demo.tscn",
	"res://Scenes/demos/three_d_traced_path_parity_demo.tscn",
	"res://Scenes/demos/three_d_vector_field_parity_demo.tscn",
	"res://Scenes/demos/three_d_parametric_curve_parity_demo.tscn",
	"res://Scenes/demos/three_d_labels_parity_demo.tscn",
	"res://Scenes/demos/three_d_grid_plane_parity_demo.tscn",
	"res://Scenes/demos/three_d_spherical_grid_parity_demo.tscn",
	"res://Scenes/demos/three_d_tube_path_parity_demo.tscn",
	"res://Scenes/demos/three_d_lathe_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_extruded_polygon_parity_demo.tscn",
	"res://Scenes/demos/three_d_bezier_curve_parity_demo.tscn",
	"res://Scenes/demos/three_d_polyhedron_parity_demo.tscn",
	"res://Scenes/demos/three_d_implicit_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_field_lines_parity_demo.tscn",
	"res://Scenes/demos/three_d_voxel_grid_parity_demo.tscn",
	"res://Scenes/demos/three_d_line_graph_parity_demo.tscn",
	"res://Scenes/demos/three_d_parametric_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_curve_network_parity_demo.tscn",
	"res://Scenes/demos/three_d_cross_section_stack_parity_demo.tscn",
	"res://Scenes/demos/three_d_spherical_harmonic_parity_demo.tscn",
	"res://Scenes/demos/three_d_surface_contours_parity_demo.tscn",
	"res://Scenes/demos/three_d_graph_network_parity_demo.tscn",
	"res://Scenes/demos/three_d_helix_bundle_parity_demo.tscn",
	"res://Scenes/demos/three_d_torus_knot_parity_demo.tscn",
	"res://Scenes/demos/three_d_ruled_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_super_shape_parity_demo.tscn",
	"res://Scenes/demos/three_d_klein_bottle_parity_demo.tscn",
	"res://Scenes/demos/three_d_seashell_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_mobius_strip_parity_demo.tscn",
	"res://Scenes/demos/three_d_minimal_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_dini_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_triply_periodic_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_wave_sphere_parity_demo.tscn",
	"res://Scenes/demos/three_d_twisted_torus_parity_demo.tscn",
	"res://Scenes/demos/three_d_kuen_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_breather_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_roman_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_whitney_umbrella_parity_demo.tscn",
	"res://Scenes/demos/three_d_cross_cap_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_monkey_saddle_surface_parity_demo.tscn",
	"res://Scenes/demos/three_d_plucker_conoid_parity_demo.tscn",
	"res://Scenes/demos/three_d_hyperbolic_paraboloid_parity_demo.tscn",
	"res://Scenes/demos/three_d_dashed_line_parity_demo.tscn",
	"res://Scenes/demos/three_d_ribbon_trail_parity_demo.tscn",
	"res://Scenes/demos/three_d_primitive_gallery_parity_demo.tscn",
	"res://Scenes/demos/three_d_stacked_systems_parity_demo.tscn",
]

const TOOL_DEMOS: Array[String] = [
	"res://Scenes/demos/demos_index.tscn",
	"res://Scenes/demos/demos_runner.tscn",
	"res://Scenes/demos/demos_smoke_check.tscn",
	"res://Scenes/demos/flat_scene_camera_parity_demo.tscn",
	"res://Scenes/demos/flat_compatible_scene_parity_demo.tscn",
	"res://Scenes/demos/tex_engine_spike_demo.tscn",
	"res://Scenes/demos/render_export_workflow_helper.tscn",
	"res://Scenes/demos/phase6_coverage_report.tscn",
	"res://Scenes/demos/phase8_coverage_report.tscn",
]


static func get_visual_demos() -> Array[String]:
	var paths: Array[String] = []
	paths.append_array(VISUAL_2D_DEMOS)
	paths.append_array(VISUAL_3D_DEMOS)
	return paths


static func get_index_demos() -> Array[String]:
	var paths: Array[String] = get_visual_demos()
	for p in TOOL_DEMOS:
		if p != "res://Scenes/demos/demos_index.tscn":
			paths.append(p)
	return paths


static func get_runner_demos() -> Array[String]:
	return get_visual_demos()


static func get_smoke_demos() -> Array[String]:
	return get_visual_demos()

